config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#top'
  get 'top/top'
  get 'quesview/index'
  get 'send/index'
  get 'teacher/index'
  post 'send/create'
  post 'answer/update'
  get 'sessions/new'
  resources :answer
  post 'answer/destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController
  before_action :set_asa, only: %i[ :index ,:update ,:destroy ]
    def index
        @questions = Question.all.page(params[:page]).per(5)
    end

    def update
        @questions = Question.find_by(params[:id])
        @questions.ans_content = params[:ans_content]
        if @questions.save
          redirect_to answer_index_path    
        end
    end

    def destroy
      @questions = Question.find_by(params[:id])
      @questions.delete
      redirect_to answer_index_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_asa
    @questions = Question.all
  end

  # Only allow a list of trusted parameters through.
  def asa_params
    params.require(:question).permit(:title, :content, :ans_title, :ans_content)
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protected
    def after_sign_in_path_for(resource)
        teacher_index_path 
    end
end

app/controllers/quesview_controller.rb
class QuesviewController < ApplicationController
    def index
        @questions = Question.all.page(params[:page]).per(5)
    end
end

app/controllers/send_controller.rb
class SendController < ApplicationController
    def new 
        @question = Question.new
        puts"作りました"
    end

    def create
        puts "ここは通常通り"
        @question = Question.new(question_params)
         if @question.save
            redirect_to quesview_index_path
            puts"完了"
         else
            puts "完全にエラーです"
         end
    end

    

    def question_params
        params.require(:question).permit(:title,:content)
    end
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def top
        render 'Top/top'
    end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quesview_helper.rb
module QuesviewHelper
end

app/helpers/send_helper.rb
module SendHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/Top/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this asa from being saved:</h2>

      <ul>
        <% asa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :タイトル %>
    <%= form.text_field :title %>
  </div>


  <div class="field">
    <%= form.label :内容 %>
    <%= form.text_field :content %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/Top/new.html.erb
<h1>質問箱</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', root_path %>

app/views/Top/top.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<div id="container"></div>
<header class="page-header" role="banner">
    <h1 class="header_title">ラムネ</h1>
</header>
<main>
    <div class="main_image">
        <div class="student-image">
            <%= image_tag 'stutent.png', class: 'student' %>          
            <p class="mouse_over_eria"></p>
            <span class="send"><%= link_to image_tag('send.png', :width => '200'), send_index_path %></span>
            <span class="view"><%= link_to image_tag('view.png'), quesview_index_path %></span>
        </div>
        <%= link_to image_tag('teacher.png', class: 'teacher'), new_user_session_path %>
    </div>
</main>
<footer></footer>
<script>
console.log("JQueryを受け入れました");
$(function() {
    let coolTime = 500;
    let animation = 600;
    let $Button = $('.student-image');

    $($Button)
        .on('mouseenter', function() {
            $(this).find('> span').stop(true).animate({
                opacity: 1,
                left: '-150px'
            }, animation, 'easeOutSine');

            $(this).find('.mouse_over_eria').stop(true).animate({
                left: '-150px'
            }, animation, 'easeOutSine');
        });

    $($Button).on('mouseleave', function() {
        $(this).find('> span').stop(true).animate({
            opacity: 0,
            left: '0px'
        }, animation, 'easeOutSine');
        $(this).find('.mouse_over_eria').stop(true).animate({
            left: '-150px'
        }, animation, 'easeOutSine');
    });

    function bubbleAnimation() {
        let $bubble = $('<span class="bubble"></span>');
        let startX = Math.floor(Math.random() * window.innerWidth); 
        let footerOffsetTop = $('.main_image').offset().top + $('.main_image').outerHeight();
        let headerOffsetTop = $('header').offset().top;

        $bubble.css({
            left: startX,
            top: 1000
        });

        $('#container').append($bubble);

        let randomSpeed_y = Math.floor(Math.random() * 200); 
        let randomSpeed = Math.floor(Math.random() * 4000) + 1000; 
        $bubble.animate({
            left: startX, 
            top: headerOffsetTop
        }, randomSpeed, 'linear', function() {
            $(this).remove();
        });
    }

    setInterval(bubbleAnimation, 500);
});
</script>

app/views/answer/index.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<%= stylesheet_link_tag 'answer', media: 'all', 'data-turbolinks-track': 'reload' %>
<html>
  <body>
  <header class="page-header" role="banner">
    <h1 class="header_title">ラムネ</h1>
  </header>
    <table>
      <tbody class="ques-list">
        <% @questions.each do |question| %>
          <tr>
          <div class="ques-item">
            <p class="title-txt"><%= question.title %><p>
            <p class="ques-txt"><%= question.content %></p>
            <div class="hidden-content">
              <%= form_with(url: answer_update_path)  do |f| %>
                  <div class="ans_sendEria"><%= f.text_area :ans_content, id: "ans_body", required: true, placeholder:"回答を記入してください"%></div>
                  <div class="ans-pos"><%= f.submit "送信", id:"ans-sendbtn" %></div>
                  
              <% end %>
            </div>
            <%= button_to  answer_path(question.id), method: :delete, id: "delete-btn", escape: false  do %>
            <div class="trash-container">
                <%= image_tag "trash.png", class: "trash" %>
                <%= image_tag "trash-open.png", class: "trash-open" %>
            </div>
            <% end %>
            <div class="E-ans-btn" id="ans-btn"><button class="ans-btn">回答する</button></div>

          </div>
          
          
          </tr>
          <% end %>
          <%= paginate @questions %>
        </tbody>
        <%= link_to '前のページ',teacher_index_path %>
        </table>

  </body>
</html>
<script>
$(function() {

    $('.ans-btn').on('click', function() {
        console.log("クリックされました");
        var $button = $(this);
        var $hiddenContent = $button.closest('.ques-item').find('.hidden-content');
        $hiddenContent.toggleClass('open');  

       
        if ($hiddenContent.hasClass('open')) {
            $button.text('Close');
            $('#ans_body').focus(); 
            console.log("クリックされました");
        } else {
            $button.text('回答する');
        }
    });
    $('#delete-btn').on('mouseover', function() {
      $(this).find('.trash-open').toggleClass('over'); 
  }).on("mouseout", function() {
      $(this).find('.trash-open').toggleClass('over'); 
  });
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Top</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Monomaniac+One&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quesview/index.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

<div id="container"></div>
<header class="page-header" role="banner">
    <h1 class="header_title">ラムネ</h1>
</header>
<main>
    <div class="ques-list">
        <% @questions.each do |question| %>            
            <div class="ques-item"> 
                <h2 class="title-txt"><%= question.title %></h2>
                <p class="ques-txt"><%= question.content %></p>
                <div class="hidden-content">
                    <h3 class="ans-title">:回答</h3>
                    <p class="ans-txt"><%= question.ans_content %></p> 
                </div>     
                <div class="button-wrapper">  
                    <button class="more-button"><p class="more-buttontxt">VIEW MORE</p></button>
                </div>
            </div>
        <% end %>
    </div>
    <%= paginate @questions %>
    <% if user_signed_in? %>
        <%= link_to '前のページ',teacher_index_path %>
    <% else %>
        <%= link_to '前のページ',root_path %>
    <% end %>
</main>

<script>
$(function() {
    $('.more-button').on('click', function() {
        console.log("クリックされました");
        var $button = $(this);
        var $hiddenContent = $button.closest('.ques-item').find('.hidden-content');
        $hiddenContent.toggleClass('open');  

       
        if ($hiddenContent.hasClass('open')) {
            $button.find('.more-buttontxt').text('close');
            console.log("クリックされましたa")
        } else {
            $button.find('.more-buttontxt').text('VIEW MORE');
        }
    });
});

</script>

app/views/send/_form.html.erb
<%= form_with(model: @question) do |form| %>
  <% if asa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this asa from being saved:</h2>

      <ul>
        <% .errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :題名 %>
    <%= form.text_field :title %>
  </div>


  <div class="field">
    <%= form.label :内容 %>
    <%= form.text_field :content %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/send/index.html.erb
<header class="page-header" role="banner">
    <h1 class="header_title">ラムネ</h1>
</header>


<div class="send-box">
<h1 class="new-h1">新しい質問を投稿</h1>
    <%= form_with url: send_create_path, local:true  do |form| %>
        <div class="send-titleeria">
            <%= form.label :title,"タイトル", class: "send-title" %>
            <%= form.text_field 'question[title]', class: "send-txt", required: true %>
        </div>

        <div class="send-txteria">
            <%= form.label :content, "内容" %>
            <%= form.text_area 'question[content]', id: "question_body", required: true %>
        </div>

        <div class="send-btn">
            <%= form.submit "質問を投稿" %>
        </div>
    <% end %>
</div>

app/views/send/new.html.erb
<h1>質問箱</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', send_index_path %>

app/views/teacher/index.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>    
<body class="teacher-page">
    <main class="selct">
        <h1 class="h-txt">どのような要件ですか？</h1>
        <h2 class="service">Service</h2>
        <div class="wrapper">
        <%= link_to answer_index_path class:"aa" do %>
            <div class="ans-form">
                <h3>01</h3>
                <p>回答</p>
            </div>
          <% end %>
        <%= link_to quesview_index_path do%>
            <div class="ans-view">
                <h3>02</h3>
                <p>回答閲覧</p>
            </div>
        <% end %>
        <%= link_to do %>
            <div class="gb-view">
                <h3>03</h3>
                <p>ゴミ箱閲覧</p>
            </div>
        <% end %>
        </div>
    </main>
</body>